<?php

use \Drupal\react_barcode_reader\TextfieldWebcam;


/*
 * Implements hook_form_alter().
 */
function react_barcode_reader_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  $fields = \Drupal\field\Entity\FieldConfig::loadMultiple();
  foreach ($fields as $field) {
    if ($field->getType() == 'string') {
      $form[$field->getName()]['#prefix'] = TextfieldWebcam\renderBlock();
    }
  }
}
